arch:
  - amd64
  - ppc64le
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
services:
  - memcached
install: python setup.py install
before_script: 
  - python -m pip install -U pip
  - python -m pip install flake8
script:
  - python -m flake8
  - nosetests
  - python -c 'import memcache; memcache._doctest()'
